# Generated by Django 5.1.3 on 2024-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affilliated_space_program', models.CharField(max_length=200)),
                ('accumulated_space_time', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
